### ISSUE TITLE
End bins cannot be interpolated, extrapolated or split

### ISSUE THREAD

**Issue by joshdunnlime** [interpretml/gam-changer#1]
When using GAM Changer on the outer/end bins, you cannot split these bins into extra bins. Also, as you cannot split this bin, it seems you cannot make a steped interpolation (either monotonic increasing or decreasing).

Finally, it would be really useful to be able to increase the domain of the EBM past the upper (lower) most value in the training domain. These are likely to be the times expert knowledge is going to be most useful, when the model cannot "see" the data.

P.s. Amazing work. This is soooo useful ⭐⭐⭐⭐⭐

**Comment by xiaohk** [comment]
Hi @joshdunnlime! Thanks for trying out GAM Changer!

You are correct that currently users cannot interpolate the last bin. This is partially because there is no *end point* for the 
last bin. Internally if the feature value is greater than the upper bound on the graph, we use the last bin's additive term to compute the prediction. Since there is no end point for the last bin, "interpolation" becomes kind of confusing.

|![image](https://user-images.githubusercontent.com/15007159/153767937-a3672d9e-59dd-4ea9-aece-08a378c7a820.png)|
|:---:|
|There is no "end point" for the last bin 👆|

I can see situations where users want to interpolate the last bin. For now you would need to manually split the last bin into two bins. 🙁 You can do that by modifying the model data. You would need to change the `additive`, `error`, `count`, and `binEdge` of `model['features'][k]`. You can create a tiny end bin by inserting `additive` (additive score), `error` (prediction variance on that bin), `count` (number of training data), `binEdge` (bin cuts).

```python
model = gc.get_model_data(ebm)
print(model['features'][0].keys())
# dict_keys(['name', 'type', 'importance', 'additive', 'error', 'id', 'count', 'binEdge', 'histEdge', 'histCount'])

print(
    len(model['features'][0]['additive']),
    len(model['features'][0]['error']),
    len(model['features'][0]['count']),
    len(model['features'][0]['binEdge']),
)
```

**Comment by xiaohk** [comment]
> When using GAM Changer on the outer/end bins, you cannot split these bins into extra bins. Also, as you cannot split this bin, it seems you cannot make a steped interpolation (either monotonic increasing or decreasing).
> 
> Finally, it would be really useful to be able to increase the domain of the EBM past the upper (lower) most value in the training domain. These are likely to be the times expert knowledge is going to be most useful, when the model cannot "see" the data.

I just saw comment. Yeah I can see how it can be very helpful to change the bin cuts in addition to bin scores. I will think more about it and perhaps design a new editing tool to hep users easily change bin definitions (like extending the last bin). Thanks for the suggestion! For now you can use the code above as a workaround. I will ping you when I have more update.

I will close the issue now. Thanks again for trying out GAM Changer and reaching out to us!!

**Comment by joshdunnlime** [comment]
That's really great. Thabnk you. This is such an awesome extension to EBMs with a lovely GUI. I was already editing some of my models in a similar way, though your suggestion seems a little neater. I hope this feedback is useful. Excited to see and hear more. This is such a great project.
