### ISSUE TITLE
Insufficient Zoom

### ISSUE THREAD

**Issue by mnaR99** [interpretml/gam-changer#8]
I don't know if this is a bug or if the zoom is just limited, but when I try to modify the function for some features that are long-tailed distributed, the points end up overlapping, and I cannot continue using the interface. 🤔 

When displaying the explanations from the interpret package, this doesn't happen because plotly has an 'infinite' zoom-in.

**Comment by xiaohk** [comment]
Hello @mnaR99, thanks for trying out GAM Changer! 

When a user zooms over the plot, we use linear interpolation to smoothly change the radius of dots, so that dots appears to have the same size after zooming. As you have noticed, the method is not perfect. 

If you are building GAM Changer from source, you can comment out the following lines to force dots to have the exact same radius value before and after zooming. It would result visually smaller dots after zooming.

https://github.com/interpretml/gam-changer/blob/d0a4cb5214125334768d23e224430aa88fc4a7f4/src/global-explanation/continuous/cont-zoom.js#L81-L85

To learn more about our zooming + scaling logic, you can see the code below:

https://github.com/interpretml/gam-changer/blob/d0a4cb5214125334768d23e224430aa88fc4a7f4/src/global-explanation/continuous/cont-zoom.js#L126-L139

I will consider exposing an API to let users control this behavior in their notebooks. I will close this issue for now. Feel free to reopen it if you have more question.
